# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page3.ui'
#
# Created by: PySide6 UI code generator
#
# WARNING: Any manual changes made to this file will be lost when pyside6-uic is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Page3(object):
    def setupUi(self, Page3):
        Page3.setObjectName("Page3")
        Page3.resize(960, 400)
        Page3.setStyleSheet("background-color: #f5f5f5;")
        
        # Main layout
        self.verticalLayout = QtWidgets.QVBoxLayout(Page3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # Header widget
        self.headerWidget = QtWidgets.QWidget(Page3)
        self.headerWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.headerWidget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.headerWidget.setStyleSheet("background-color: #5a5a8a; color: white;")
        self.headerWidget.setObjectName("headerWidget")
        
        self.headerLayout = QtWidgets.QHBoxLayout(self.headerWidget)
        self.headerLayout.setContentsMargins(20, 0, 20, 0)
        self.headerLayout.setObjectName("headerLayout")
        
        # Blocked status indicator
        self.blockedWidget = QtWidgets.QWidget(self.headerWidget)
        self.blockedWidget.setMinimumSize(QtCore.QSize(100, 30))
        self.blockedWidget.setMaximumSize(QtCore.QSize(100, 30))
        self.blockedWidget.setStyleSheet("""
            background-color: #6a4c93;
            border-radius: 15px;
            color: white;
            font-weight: bold;
        """)
        self.blockedWidget.setObjectName("blockedWidget")
        
        self.blockedLayout = QtWidgets.QHBoxLayout(self.blockedWidget)
        self.blockedLayout.setContentsMargins(15, 0, 15, 0)
        self.blockedLayout.setObjectName("blockedLayout")
        
        # Red indicator circle
        self.redIndicator = QtWidgets.QLabel(self.blockedWidget)
        self.redIndicator.setMinimumSize(QtCore.QSize(12, 12))
        self.redIndicator.setMaximumSize(QtCore.QSize(12, 12))
        self.redIndicator.setStyleSheet("""
            background-color: #ff4444;
            border-radius: 6px;
        """)
        self.redIndicator.setObjectName("redIndicator")
        self.blockedLayout.addWidget(self.redIndicator)
        
        # Blocked label
        self.blockedLabel = QtWidgets.QLabel(self.blockedWidget)
        self.blockedLabel.setText("Blocked")
        self.blockedLabel.setStyleSheet("color: white; font-weight: bold;")
        self.blockedLabel.setObjectName("blockedLabel")
        self.blockedLayout.addWidget(self.blockedLabel)
        
        self.headerLayout.addWidget(self.blockedWidget)
        
        # Spacer
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        
        # Green indicator
        self.greenIndicator = QtWidgets.QLabel(self.headerWidget)
        self.greenIndicator.setMinimumSize(QtCore.QSize(12, 12))
        self.greenIndicator.setMaximumSize(QtCore.QSize(12, 12))
        self.greenIndicator.setStyleSheet("""
            background-color: #44ff44;
            border-radius: 6px;
        """)
        self.greenIndicator.setObjectName("greenIndicator")
        self.headerLayout.addWidget(self.greenIndicator)
        
        self.verticalLayout.addWidget(self.headerWidget)
        
        # Table widget
        self.tableWidget = QtWidgets.QTableWidget(Page3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        
        # Set headers
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        
        # Table styling
        self.tableWidget.setStyleSheet("""
            QTableWidget {
                gridline-color: #e0e0e0;
                background-color: white;
                alternate-background-color: #f8f8f8;
            }
            QTableWidget::item {
                padding: 10px;
                border-bottom: 1px solid #e0e0e0;
            }
            QHeaderView::section {
                background-color: #5a5a8a;
                color: white;
                padding: 10px;
                border: none;
                font-weight: bold;
            }
            QTableWidget::item:selected {
                background-color: #e3f2fd;
            }
        """)
        
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        
        self.verticalLayout.addWidget(self.tableWidget)
        
        self.retranslateUi(Page3)
        QtCore.QMetaObject.connectSlotsByName(Page3)

    def retranslateUi(self, Page3):
        _translate = QtCore.QCoreApplication.translate
        Page3.setWindowTitle(_translate("Page3", "Security Log"))
        
        # Set header labels
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Page3", ""))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Page3", "Source IP"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Page3", "Destination IP"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Page3", "Event Type"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Page3", "Description"))