name: Notify Discord on Push to Main

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Discord
      uses: sarisia/actions-status-discord@v1
      with:
        title: Pushed
        webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
        color: 00FF00
